version: '3'
services:
  app:
    build: .
    ports:
      - "3500:3500"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run dev
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8083:8081"
    environment: 
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
